// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LogBean.proto

package com.doit.once.pojo;

public final class LogBeansProto {
  private LogBeansProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LogBeansOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogBeans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    java.util.List<LogBean>
        getLogBeansList();
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    LogBean getLogBeans(int index);
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    int getLogBeansCount();
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    java.util.List<? extends LogBeanOrBuilder>
        getLogBeansOrBuilderList();
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    LogBeanOrBuilder getLogBeansOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code LogBeans}
   */
  public  static final class LogBeans extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogBeans)
      LogBeansOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogBeans.newBuilder() to construct.
    private LogBeans(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogBeans() {
      logBeans_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogBeans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                logBeans_ = new java.util.ArrayList<LogBean>();
                mutable_bitField0_ |= 0x00000001;
              }
              logBeans_.add(
                  input.readMessage(LogBean.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          logBeans_ = java.util.Collections.unmodifiableList(logBeans_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogBeansProto.internal_static_LogBeans_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogBeansProto.internal_static_LogBeans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogBeans.class, Builder.class);
    }

    public static final int LOGBEANS_FIELD_NUMBER = 1;
    private java.util.List<LogBean> logBeans_;
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    public java.util.List<LogBean> getLogBeansList() {
      return logBeans_;
    }
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    public java.util.List<? extends LogBeanOrBuilder>
        getLogBeansOrBuilderList() {
      return logBeans_;
    }
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    public int getLogBeansCount() {
      return logBeans_.size();
    }
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    public LogBean getLogBeans(int index) {
      return logBeans_.get(index);
    }
    /**
     * <code>repeated .LogBean logBeans = 1;</code>
     */
    public LogBeanOrBuilder getLogBeansOrBuilder(
        int index) {
      return logBeans_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < logBeans_.size(); i++) {
        output.writeMessage(1, logBeans_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < logBeans_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, logBeans_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LogBeans)) {
        return super.equals(obj);
      }
      LogBeans other = (LogBeans) obj;

      if (!getLogBeansList()
          .equals(other.getLogBeansList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getLogBeansCount() > 0) {
        hash = (37 * hash) + LOGBEANS_FIELD_NUMBER;
        hash = (53 * hash) + getLogBeansList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LogBeans parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogBeans parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogBeans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogBeans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogBeans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogBeans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogBeans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogBeans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogBeans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LogBeans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogBeans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogBeans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LogBeans prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogBeans}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogBeans)
        LogBeansOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogBeansProto.internal_static_LogBeans_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogBeansProto.internal_static_LogBeans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogBeans.class, Builder.class);
      }

      // Construct using com.doit.once.pojo.LogBeansProto.LogBeans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLogBeansFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (logBeansBuilder_ == null) {
          logBeans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          logBeansBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LogBeansProto.internal_static_LogBeans_descriptor;
      }

      @Override
      public LogBeans getDefaultInstanceForType() {
        return LogBeans.getDefaultInstance();
      }

      @Override
      public LogBeans build() {
        LogBeans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LogBeans buildPartial() {
        LogBeans result = new LogBeans(this);
        int from_bitField0_ = bitField0_;
        if (logBeansBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            logBeans_ = java.util.Collections.unmodifiableList(logBeans_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.logBeans_ = logBeans_;
        } else {
          result.logBeans_ = logBeansBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LogBeans) {
          return mergeFrom((LogBeans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LogBeans other) {
        if (other == LogBeans.getDefaultInstance()) return this;
        if (logBeansBuilder_ == null) {
          if (!other.logBeans_.isEmpty()) {
            if (logBeans_.isEmpty()) {
              logBeans_ = other.logBeans_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLogBeansIsMutable();
              logBeans_.addAll(other.logBeans_);
            }
            onChanged();
          }
        } else {
          if (!other.logBeans_.isEmpty()) {
            if (logBeansBuilder_.isEmpty()) {
              logBeansBuilder_.dispose();
              logBeansBuilder_ = null;
              logBeans_ = other.logBeans_;
              bitField0_ = (bitField0_ & ~0x00000001);
              logBeansBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLogBeansFieldBuilder() : null;
            } else {
              logBeansBuilder_.addAllMessages(other.logBeans_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LogBeans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LogBeans) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<LogBean> logBeans_ =
        java.util.Collections.emptyList();
      private void ensureLogBeansIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          logBeans_ = new java.util.ArrayList<LogBean>(logBeans_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          LogBean, LogBean.Builder, LogBeanOrBuilder> logBeansBuilder_;

      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public java.util.List<LogBean> getLogBeansList() {
        if (logBeansBuilder_ == null) {
          return java.util.Collections.unmodifiableList(logBeans_);
        } else {
          return logBeansBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public int getLogBeansCount() {
        if (logBeansBuilder_ == null) {
          return logBeans_.size();
        } else {
          return logBeansBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public LogBean getLogBeans(int index) {
        if (logBeansBuilder_ == null) {
          return logBeans_.get(index);
        } else {
          return logBeansBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder setLogBeans(
          int index, LogBean value) {
        if (logBeansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogBeansIsMutable();
          logBeans_.set(index, value);
          onChanged();
        } else {
          logBeansBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder setLogBeans(
          int index, LogBean.Builder builderForValue) {
        if (logBeansBuilder_ == null) {
          ensureLogBeansIsMutable();
          logBeans_.set(index, builderForValue.build());
          onChanged();
        } else {
          logBeansBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder addLogBeans(LogBean value) {
        if (logBeansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogBeansIsMutable();
          logBeans_.add(value);
          onChanged();
        } else {
          logBeansBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder addLogBeans(
          int index, LogBean value) {
        if (logBeansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogBeansIsMutable();
          logBeans_.add(index, value);
          onChanged();
        } else {
          logBeansBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder addLogBeans(
          LogBean.Builder builderForValue) {
        if (logBeansBuilder_ == null) {
          ensureLogBeansIsMutable();
          logBeans_.add(builderForValue.build());
          onChanged();
        } else {
          logBeansBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder addLogBeans(
          int index, LogBean.Builder builderForValue) {
        if (logBeansBuilder_ == null) {
          ensureLogBeansIsMutable();
          logBeans_.add(index, builderForValue.build());
          onChanged();
        } else {
          logBeansBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder addAllLogBeans(
          Iterable<? extends LogBean> values) {
        if (logBeansBuilder_ == null) {
          ensureLogBeansIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, logBeans_);
          onChanged();
        } else {
          logBeansBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder clearLogBeans() {
        if (logBeansBuilder_ == null) {
          logBeans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          logBeansBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public Builder removeLogBeans(int index) {
        if (logBeansBuilder_ == null) {
          ensureLogBeansIsMutable();
          logBeans_.remove(index);
          onChanged();
        } else {
          logBeansBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public LogBean.Builder getLogBeansBuilder(
          int index) {
        return getLogBeansFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public LogBeanOrBuilder getLogBeansOrBuilder(
          int index) {
        if (logBeansBuilder_ == null) {
          return logBeans_.get(index);  } else {
          return logBeansBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public java.util.List<? extends LogBeanOrBuilder>
           getLogBeansOrBuilderList() {
        if (logBeansBuilder_ != null) {
          return logBeansBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(logBeans_);
        }
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public LogBean.Builder addLogBeansBuilder() {
        return getLogBeansFieldBuilder().addBuilder(
            LogBean.getDefaultInstance());
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public LogBean.Builder addLogBeansBuilder(
          int index) {
        return getLogBeansFieldBuilder().addBuilder(
            index, LogBean.getDefaultInstance());
      }
      /**
       * <code>repeated .LogBean logBeans = 1;</code>
       */
      public java.util.List<LogBean.Builder>
           getLogBeansBuilderList() {
        return getLogBeansFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          LogBean, LogBean.Builder, LogBeanOrBuilder>
          getLogBeansFieldBuilder() {
        if (logBeansBuilder_ == null) {
          logBeansBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              LogBean, LogBean.Builder, LogBeanOrBuilder>(
                  logBeans_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          logBeans_ = null;
        }
        return logBeansBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LogBeans)
    }

    // @@protoc_insertion_point(class_scope:LogBeans)
    private static final LogBeans DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogBeans();
    }

    public static LogBeans getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogBeans>
        PARSER = new com.google.protobuf.AbstractParser<LogBeans>() {
      @Override
      public LogBeans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogBeans(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogBeans> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LogBeans> getParserForType() {
      return PARSER;
    }

    @Override
    public LogBeans getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogBeanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogBean)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uid = 1;</code>
     */
    String getUid();
    /**
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <code>string event_id = 2;</code>
     */
    String getEventId();
    /**
     * <code>string event_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getEventIdBytes();

    /**
     * <code>string event_name = 3;</code>
     */
    String getEventName();
    /**
     * <code>string event_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getEventNameBytes();

    /**
     * <code>string province = 4;</code>
     */
    String getProvince();
    /**
     * <code>string province = 4;</code>
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    /**
     * <code>string city = 5;</code>
     */
    String getCity();
    /**
     * <code>string city = 5;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string district = 6;</code>
     */
    String getDistrict();
    /**
     * <code>string district = 6;</code>
     */
    com.google.protobuf.ByteString
        getDistrictBytes();

    /**
     * <code>double longitude = 7;</code>
     */
    double getLongitude();

    /**
     * <code>double latitude = 8;</code>
     */
    double getLatitude();
  }
  /**
   * Protobuf type {@code LogBean}
   */
  public  static final class LogBean extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogBean)
      LogBeanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogBean.newBuilder() to construct.
    private LogBean(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogBean() {
      uid_ = "";
      eventId_ = "";
      eventName_ = "";
      province_ = "";
      city_ = "";
      district_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              eventId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              eventName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              province_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              district_ = s;
              break;
            }
            case 57: {

              longitude_ = input.readDouble();
              break;
            }
            case 65: {

              latitude_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LogBeansProto.internal_static_LogBean_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LogBeansProto.internal_static_LogBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogBean.class, Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile Object uid_;
    /**
     * <code>string uid = 1;</code>
     */
    public String getUid() {
      Object ref = uid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_ID_FIELD_NUMBER = 2;
    private volatile Object eventId_;
    /**
     * <code>string event_id = 2;</code>
     */
    public String getEventId() {
      Object ref = eventId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      }
    }
    /**
     * <code>string event_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_NAME_FIELD_NUMBER = 3;
    private volatile Object eventName_;
    /**
     * <code>string event_name = 3;</code>
     */
    public String getEventName() {
      Object ref = eventName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      }
    }
    /**
     * <code>string event_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      Object ref = eventName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVINCE_FIELD_NUMBER = 4;
    private volatile Object province_;
    /**
     * <code>string province = 4;</code>
     */
    public String getProvince() {
      Object ref = province_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        province_ = s;
        return s;
      }
    }
    /**
     * <code>string province = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 5;
    private volatile Object city_;
    /**
     * <code>string city = 5;</code>
     */
    public String getCity() {
      Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISTRICT_FIELD_NUMBER = 6;
    private volatile Object district_;
    /**
     * <code>string district = 6;</code>
     */
    public String getDistrict() {
      Object ref = district_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        district_ = s;
        return s;
      }
    }
    /**
     * <code>string district = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDistrictBytes() {
      Object ref = district_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        district_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGITUDE_FIELD_NUMBER = 7;
    private double longitude_;
    /**
     * <code>double longitude = 7;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int LATITUDE_FIELD_NUMBER = 8;
    private double latitude_;
    /**
     * <code>double latitude = 8;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (!getEventIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventId_);
      }
      if (!getEventNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, eventName_);
      }
      if (!getProvinceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, province_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, city_);
      }
      if (!getDistrictBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, district_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(7, longitude_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(8, latitude_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (!getEventIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventId_);
      }
      if (!getEventNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, eventName_);
      }
      if (!getProvinceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, province_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, city_);
      }
      if (!getDistrictBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, district_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, longitude_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, latitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LogBean)) {
        return super.equals(obj);
      }
      LogBean other = (LogBean) obj;

      if (!getUid()
          .equals(other.getUid())) return false;
      if (!getEventId()
          .equals(other.getEventId())) return false;
      if (!getEventName()
          .equals(other.getEventName())) return false;
      if (!getProvince()
          .equals(other.getProvince())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getDistrict()
          .equals(other.getDistrict())) return false;
      if (Double.doubleToLongBits(getLongitude())
          != Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (Double.doubleToLongBits(getLatitude())
          != Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEventId().hashCode();
      hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getEventName().hashCode();
      hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
      hash = (53 * hash) + getProvince().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + DISTRICT_FIELD_NUMBER;
      hash = (53 * hash) + getDistrict().hashCode();
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLatitude()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LogBean parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogBean parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LogBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LogBean prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogBean)
        LogBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LogBeansProto.internal_static_LogBean_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LogBeansProto.internal_static_LogBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogBean.class, Builder.class);
      }

      // Construct using com.doit.once.pojo.LogBeansProto.LogBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        uid_ = "";

        eventId_ = "";

        eventName_ = "";

        province_ = "";

        city_ = "";

        district_ = "";

        longitude_ = 0D;

        latitude_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LogBeansProto.internal_static_LogBean_descriptor;
      }

      @Override
      public LogBean getDefaultInstanceForType() {
        return LogBean.getDefaultInstance();
      }

      @Override
      public LogBean build() {
        LogBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LogBean buildPartial() {
        LogBean result = new LogBean(this);
        result.uid_ = uid_;
        result.eventId_ = eventId_;
        result.eventName_ = eventName_;
        result.province_ = province_;
        result.city_ = city_;
        result.district_ = district_;
        result.longitude_ = longitude_;
        result.latitude_ = latitude_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LogBean) {
          return mergeFrom((LogBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LogBean other) {
        if (other == LogBean.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getEventId().isEmpty()) {
          eventId_ = other.eventId_;
          onChanged();
        }
        if (!other.getEventName().isEmpty()) {
          eventName_ = other.eventName_;
          onChanged();
        }
        if (!other.getProvince().isEmpty()) {
          province_ = other.province_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getDistrict().isEmpty()) {
          district_ = other.district_;
          onChanged();
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LogBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LogBean) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object uid_ = "";
      /**
       * <code>string uid = 1;</code>
       */
      public String getUid() {
        Object ref = uid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {

        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        uid_ = value;
        onChanged();
        return this;
      }

      private Object eventId_ = "";
      /**
       * <code>string event_id = 2;</code>
       */
      public String getEventId() {
        Object ref = eventId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          eventId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string event_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEventIdBytes() {
        Object ref = eventId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          eventId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_id = 2;</code>
       */
      public Builder setEventId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        eventId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_id = 2;</code>
       */
      public Builder clearEventId() {

        eventId_ = getDefaultInstance().getEventId();
        onChanged();
        return this;
      }
      /**
       * <code>string event_id = 2;</code>
       */
      public Builder setEventIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        eventId_ = value;
        onChanged();
        return this;
      }

      private Object eventName_ = "";
      /**
       * <code>string event_name = 3;</code>
       */
      public String getEventName() {
        Object ref = eventName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          eventName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEventNameBytes() {
        Object ref = eventName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          eventName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public Builder setEventName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        eventName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public Builder clearEventName() {

        eventName_ = getDefaultInstance().getEventName();
        onChanged();
        return this;
      }
      /**
       * <code>string event_name = 3;</code>
       */
      public Builder setEventNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        eventName_ = value;
        onChanged();
        return this;
      }

      private Object province_ = "";
      /**
       * <code>string province = 4;</code>
       */
      public String getProvince() {
        Object ref = province_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          province_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string province = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        Object ref = province_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string province = 4;</code>
       */
      public Builder setProvince(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        province_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string province = 4;</code>
       */
      public Builder clearProvince() {

        province_ = getDefaultInstance().getProvince();
        onChanged();
        return this;
      }
      /**
       * <code>string province = 4;</code>
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        province_ = value;
        onChanged();
        return this;
      }

      private Object city_ = "";
      /**
       * <code>string city = 5;</code>
       */
      public String getCity() {
        Object ref = city_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string city = 5;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 5;</code>
       */
      public Builder setCity(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 5;</code>
       */
      public Builder clearCity() {

        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>string city = 5;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        city_ = value;
        onChanged();
        return this;
      }

      private Object district_ = "";
      /**
       * <code>string district = 6;</code>
       */
      public String getDistrict() {
        Object ref = district_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          district_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string district = 6;</code>
       */
      public com.google.protobuf.ByteString
          getDistrictBytes() {
        Object ref = district_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          district_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string district = 6;</code>
       */
      public Builder setDistrict(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        district_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string district = 6;</code>
       */
      public Builder clearDistrict() {

        district_ = getDefaultInstance().getDistrict();
        onChanged();
        return this;
      }
      /**
       * <code>string district = 6;</code>
       */
      public Builder setDistrictBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        district_ = value;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 7;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 7;</code>
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 7;</code>
       */
      public Builder clearLongitude() {

        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 8;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 8;</code>
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 8;</code>
       */
      public Builder clearLatitude() {

        latitude_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LogBean)
    }

    // @@protoc_insertion_point(class_scope:LogBean)
    private static final LogBean DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogBean();
    }

    public static LogBean getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogBean>
        PARSER = new com.google.protobuf.AbstractParser<LogBean>() {
      @Override
      public LogBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogBean(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogBean> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LogBean> getParserForType() {
      return PARSER;
    }

    @Override
    public LogBean getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogBeans_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogBeans_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogBean_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rLogBean.proto\"&\n\010LogBeans\022\032\n\010logBeans\030" +
      "\001 \003(\0132\010.LogBean\"\223\001\n\007LogBean\022\013\n\003uid\030\001 \001(\t" +
      "\022\020\n\010event_id\030\002 \001(\t\022\022\n\nevent_name\030\003 \001(\t\022\020" +
      "\n\010province\030\004 \001(\t\022\014\n\004city\030\005 \001(\t\022\020\n\010distri" +
      "ct\030\006 \001(\t\022\021\n\tlongitude\030\007 \001(\001\022\020\n\010latitude\030" +
      "\010 \001(\001B#\n\022com.doit.once.pojoB\rLogBeansPro" +
      "tob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LogBeans_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LogBeans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogBeans_descriptor,
        new String[] { "LogBeans", });
    internal_static_LogBean_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LogBean_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogBean_descriptor,
        new String[] { "Uid", "EventId", "EventName", "Province", "City", "District", "Longitude", "Latitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
